### ISSUE TITLE
Documentation Seems to be Lacking

### ISSUE THREAD

**Issue by MycoMap** [WFSRDataScience/PIMENTA#3]
in the settings file, there is no explanation on what is required for the following:

##MARKERS TO ANALYSE
Targets=""

#File containing marker primer sequences
PrimerFile=

**Comment by MycoMap** [comment]
FIrst attempt to run failed because dos2unix was not installed.
sudo apt install dos2unix

**Comment by MycoMap** [comment]
Stuck here:

Run_DNA-metabarcoding-MINION.ITSFungal.sh: line 170: module: command not found
Run_DNA-metabarcoding-MINION.ITSFungal.sh: line 171: module: command not found

**Comment by MycoMap** [comment]
Also I do not see an input for a barcode/index file. Does this only work with ONT barcodes?

**Comment by valerievandervorst** [comment]
Hi,

There is a readthedocs website dedicated to PIMENTA of which the link is also included in the "About" section of this repository:
https://pimenta.readthedocs.io/en/latest/

**Comment by valerievandervorst** [comment]
> Stuck here:
> 
> Run_DNA-metabarcoding-MINION.ITSFungal.sh: line 170: module: command not found Run_DNA-metabarcoding-MINION.ITSFungal.sh: line 171: module: command not found

It seems I still included the fix for the HPC I use, I for now removed this part. It should not cause an issue for the pipeline, this fix tried to reload a (slurm) module, but is not required.
